# Generated by Django 6.0.6 on 2026-06-30 22:39

import django.db.models.deletion
from django.db import migrations, models


def create_default_category(apps, schema_editor):
    Category = apps.get_model('recipes', 'Category')
    Category.objects.get_or_create(
        pk=1,
        defaults={'name': 'Uncategorized'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_category, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Temps en minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.category'),
            preserve_default=False,
        ),
    ]
