# Generated by Django 6.0.6 on 2026-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de cuisson en minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Coût estimé en euros', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la recette', null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='private_notes',
            field=models.TextField(blank=True, help_text="Notes privées visibles uniquement par l'auteur"),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules (ex: vegan, sans-gluten, rapide)', max_length=200),
        ),
    ]
